#!/bin/bash
SIZ=32; x=0; y=0
color=0; cl=0

if ! [ -z $1 ];then SIZ=$1; fi

if ! [ -z $2 ];then
 if [ $2 -gt 8 ];then
  color=1
 else
  tput setaf $2;
 fi
fi

while [ $y -lt $((SIZ/2)) ]; do
 char=$(($RANDOM%94+32))
 if [ $color -eq 1 ];then cl=$(($RANDOM%8)); tput setaf $cl; fi
 printf "\x$(printf %x $char)"; x=$((x+1))
 if [ $x -eq $SIZ ]; then
  printf "\n"; y=$((y+1)); x=0
 fi
done

tput sgr0
exit 0
